name: Spoons Game CI/CD Workflow
run-name: ${{ github.actor }} | ${{ github.ref }}

on:
  push:

jobs:
  run-unit-test-and-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: ./gradlew test

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/testDebugUnitTest/



